name: check24-tippspiel-challenge

services:
  keycloak:
    restart: always
    build:
      context: ./docker/keycloak
      dockerfile: Dockerfile
      target: development
    ports:
      - "8080:8080"
    command:
      - start-dev
      - --db=postgres
      - --import-realm
      - -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
      - --transaction-xa-enabled=false
    depends_on:
      db:
        condition: service_healthy
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: password
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/server.crt.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/server.key.pem
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    volumes:
      - ./docker/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
      - ./docker/keycloak/server.crt.pem:/opt/keycloak/conf/server.crt.pem:ro
      - ./docker/keycloak/server.key.pem:/opt/keycloak/conf/server.key.pem:ro
    networks:
      - client
      - server

  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - node-modules-client:/app/node_modules/
    healthcheck:
      test: "curl -f http://localhost:3000 || exit 1"
      interval: 5s
    entrypoint: npm run dev
    networks:
      - client
      - server

  storybook:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    ports:
      - "6006:6006"
    volumes:
      - ./client:/app
      - node-modules-storybook:/app/node_modules/
    healthcheck:
      test: "curl -f http://localhost:6006 || exit 1"
      interval: 5s
    working_dir: /app
    command: npm run storybook
    networks:
      - client

  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    entrypoint: CompileDaemon -build="go build -o /build/server" -command="/build/server"
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    networks:
      - server

  db:
    restart: always
    build:
      context: ./docker/postgresql
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U root -d master'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - server

  kafka:
    restart: always
    build:
      context: ./docker/kafka
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
      - "9094:9094"
    healthcheck:
      test: kafka-topics.sh --list --bootstrap-server localhost:9092 || exit 1
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - kafka-data:/bitnami"
    networks:
      - client
      - server
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://kafka:9094
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - BITNAMI_DEBUG=yes
      - KAFKA_CFG_NUM_PARTITIONS=2

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8081:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    networks:
      - server
    volumes:
      - ~/kafka-ui/config.yml:/etc/kafkaui/dynamic_config.yaml

networks:
  client:
  server:

volumes:
  node-modules-client:
  node-modules-storybook:
  db-data:
  kafka-data: