name: check24-tippspiel-challenge
version: "3.9"

services:
  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    ports:
    - "3000:3000"
    volumes:
      - ./client:/app
      - node-modules-client:/app/node_modules/
    healthcheck:
      test: "curl -f http://localhost:3000 || exit 1"
      interval: 5s
    entrypoint: npm run dev
    networks:
      - client
      - server

  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    entrypoint: CompileDaemon -build="go build -o /build/server" -command="/build/server"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    networks:
      - server

  db:
    restart: always
    build:
      context: ./docker/postgresql
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U root -d dev'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - server

networks:
  client:
  server:

volumes:
  node-modules-client:
  db-data: