version: '3'

tasks:
  build-containers:
    desc: Build containers
    aliases: [ build ]
    cmds:
      - docker compose build {{.CLI_ARGS}}

  up:
    desc: Start the containers
    aliases: [ start ]
    cmds:
      - docker compose up -d {{.CLI_ARGS}}

  down:
    desc: Stop the containers
    aliases: [ stop ]
    cmds:
      - docker compose down {{.CLI_ARGS}}

  restart:
    desc: Restart the containers
    cmds:
      - docker compose down {{.CLI_ARGS}}
      - docker compose up -d {{.CLI_ARGS}}

  down-volume:
    desc: Stop the containers and remove all volumes
    aliases: [ downv ]
    cmds:
      - docker compose down -v

  generate-api-client:
    aliases: [ generate-client ]
    desc: Run openapi generator
    deps:
      - task: up
        vars: { CLI_ARGS: 'server' }
    cmds:
      - docker compose run --rm --entrypoint="npm run generate-api-client" client

  format:
    desc: Run formatter
    aliases: [ fmt ]
    cmds:
      - docker compose run --rm --entrypoint="npm run fmt" client

  lint:
    desc: Run linter
    cmds:
      - docker compose run --rm --entrypoint="npm run lint ." client

  logs:
    desc: View logs
    cmds:
      - docker compose logs -f {{.CLI_ARGS}}

  k8s-up:
    desc: Create k8s cluster
    cmds:
      - kind create cluster --config ./deployment/kind-config.yaml --name check24-tippspiel-challenge
      - kubectl apply --filename https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml
      - |
        while ! kubectl -n ingress-nginx describe pod ingress-nginx --request-timeout "5s" &> /dev/null; do sleep 5; done
      - kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=180s
      - skaffold dev
      - task: k8s-down

  k8s-down:
    desc: Delete k8s cluster
    cmds:
      - kind delete cluster --name check24-tippspiel-challenge