version: '3'

tasks:
  build-containers:
    desc: Build containers
    aliases: [ build ]
    cmds:
      - docker compose build {{.CLI_ARGS}}

  up:
    desc: Start the containers
    aliases: [ start ]
    cmds:
      - docker compose up -d {{.CLI_ARGS}}

  down:
    desc: Stop the containers
    aliases: [ stop ]
    cmds:
      - docker compose down {{.CLI_ARGS}}

  restart:
    desc: Restart the containers
    cmds:
      - docker compose down {{.CLI_ARGS}}
      - docker compose up -d {{.CLI_ARGS}}

  down-volume:
    desc: Stop the containers and remove all volumes
    aliases: [ downv ]
    cmds:
      - docker compose down -v

  format:
    desc: Run formatter
    aliases: [ fmt ]
    cmds:
      - docker compose run --rm --entrypoint="npm run fmt" client

  lint:
    desc: Run linter
    cmds:
      - docker compose run --rm --entrypoint="npm run lint ." client

  logs:
    desc: View logs
    cmds:
      - docker compose logs -f {{.CLI_ARGS}}