definitions:
  handler.communitiesResponse:
    properties:
      communities:
        items:
          $ref: '#/definitions/handler.communityResponse'
        type: array
    type: object
  handler.communityCreateRequest:
    properties:
      community:
        properties:
          name:
            type: string
        type: object
    type: object
  handler.communityResponse:
    properties:
      community:
        properties:
          id:
            type: string
          name:
            type: string
        type: object
    type: object
  handler.rootResponse:
    properties:
      message:
        type: string
    type: object
  handler.userResponse:
    properties:
      user:
        properties:
          email:
            type: string
          firstName:
            type: string
          id:
            type: string
          lastName:
            type: string
          username:
            type: string
        type: object
    type: object
info:
  contact: {}
  title: Check24 Tippspiel Challenge
  version: "1.0"
paths:
  /:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.rootResponse'
      summary: Example
      tags:
      - Root
  /v1/communities:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.communitiesResponse'
      security:
      - OAuth2Implicit: []
      summary: Retrieve all communities the current user is part of
      tags:
      - Communities
    post:
      consumes:
      - application/json
      parameters:
      - description: Create Community
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/handler.communityCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.communityResponse'
      security:
      - OAuth2Implicit: []
      summary: Create a new community
      tags:
      - Communities
  /v1/communities/{community_id}/join:
    post:
      parameters:
      - description: Community ID
        in: path
        name: community_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.communityResponse'
      security:
      - OAuth2Implicit: []
      summary: Join the specified community
      tags:
      - Communities
  /v1/users/me:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.userResponse'
      security:
      - OAuth2Implicit: []
      summary: Get current user
      tags:
      - Users
securityDefinitions:
  OAuth2Implicit:
    authorizationUrl: http://localhost:8080/realms/development/protocol/openid-connect/auth
    flow: implicit
    type: oauth2
swagger: "2.0"
