definitions:
  model.RootResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  title: Check24 Tippspiel Challenge
  version: "1.0"
paths:
  /:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.RootResponse'
      security:
      - OAuth2Implicit: []
      summary: Get Root
securityDefinitions:
  OAuth2Implicit:
    authorizationUrl: http://localhost:8080/realms/development/protocol/openid-connect/auth
    flow: implicit
    type: oauth2
swagger: "2.0"
