import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import SessionGuard from "@/components/auth/session-guard/SessionGuard";
import Navigation from "@/components/navigation/Navigation";
import React from "react";
import { Toaster } from "@/components/toast/Toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-colors-white text-gray-12`}>
        <Providers>
          <SessionGuard>
            <Navigation>
              {children}
              <Toaster />
            </Navigation>
          </SessionGuard>
        </Providers>
      </body>
    </html>
  );
}
