# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployments:
  client:
    replicas: 1
    image:
      repository: "check24-tippspiel-challenge/client"
      tag: "latest"
    containerPort: 3000
    env:
      - name: KEYCLOAK_CLIENT_ID
        value: webclient
      - name: KEYCLOAK_ISSUER
        value: "http://{{ .Chart.Name }}-keycloak-cluster-ip-service:8080/realms/development"
      - name: NEXTAUTH_URL
        value: http://local.gendev.leonliang.lu
      - name: KEYCLOAK_CLIENT_SECRET
        value: SXiMvr1GG10bk2J63ODZC9SOaoAZ4dbe
      - name: NEXTAUTH_SECRET
        value: feZJWB3mcQ93VBmqHKQI5er5NEIxcDPb3wtT/KaLB9s=

  server:
    replicas: 1
    image:
      repository: "check24-tippspiel-challenge/server"
      tag: "latest"
    containerPort: 8000
    env:
      - name: AUTH_SERVER_URL
        value: "http://{{ .Chart.Name }}-keycloak-cluster-ip-service:8080"
      - name: AUTH_CLIENT_ID
        value: webclient
      - name: AUTH_CLIENT_SECRET
        value: SXiMvr1GG10bk2J63ODZC9SOaoAZ4dbe
      - name: AUTH_REALM
        value: development
      - name: POSTGRES_HOST
        value: "{{ .Chart.Name }}-postgresql-cluster-ip-service"
      - name: POSTGRES_PORT
        value: "{{ .Values.services.postgresql.port | quote }}"
      - name: POSTGRES_DB
        value: master
      - name: POSTGRES_USER
        value: root
      - name: POSTGRES_PASSWORD
        value: password

  keycloak:
    replicas: 1
    image:
      repository: "check24-tippspiel-challenge/keycloak"
      tag: "latest"
    containerPort: 8080
    env:
      - name: KC_PROXY
        value: edge
      - name: KC_DB
        value: postgres
      - name: KC_DB_USERNAME
        value: root
      - name: KC_DB_PASSWORD
        value: password
      - name: KC_HTTPS_CERTIFICATE_FILE
        value: /opt/keycloak/conf/server.crt.pem
      - name: KC_HTTPS_CERTIFICATE_KEY_FILE
        value: /opt/keycloak/conf/server.key.pem
      - name: KEYCLOAK_ADMIN
        value: admin
      - name: KEYCLOAK_ADMIN_PASSWORD
        value: password
      - name: KC_DB_URL
        value: "jdbc:postgresql://{{ .Chart.Name }}-postgresql-cluster-ip-service:5432/master"
      - name: KC_HOSTNAME
        value: "{{ .Values.services.ingress.authHost }}"
  postgresql:
    replicas: 1
    image:
      repository: "check24-tippspiel-challenge/db"
      tag: "latest"
    containerPort: 5432
    volumes:
      name: postgresql-storage
    volumeMounts:
      mountPath: /var/lib/postgresql/data
      name: postgresql-storage
    env:
      - name: POSTGRES_USER
        value: root
      - name: POSTGRES_PASSWORD
        value: password
      - name: POSTGRES_DB
        value: master

services:
  client:
    type: ClusterIP
    port: 3000
  server:
    type: ClusterIP
    port: 8000
  keycloak:
    type: ClusterIP
    port: 8080
  postgresql:
    type: ClusterIP
    port: 5432
  ingress:
    clientHost: local.gendev.leonliang.lu
    authHost: auth.local.gendev.leonliang.lu
    serverHost: api.local.gendev.leonliang.lu

persistentVolumeClaim:
  database:
    accessModes: ReadWriteOnce
    requestedStorage: 2Gi