name: Create and publish Docker images

on:
  push:
    branches:
      - release
env:
  DOCKER_HUB_NAMESPACE: liangleon
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env.local file (client)
        run: |
          cd client
          touch .env.local
          echo KEYCLOAK_CLIENT_SECRET=${{ secrets.KEYCLOAK_CLIENT_SECRET }} >> .env.local
          echo NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} >> .env.local
          cat .env.local

      - name: Create .env file (server)
        run: |
          cd server
          touch .env
          echo ENVIRONMENT=production >> .env
          echo AUTH_SERVER_URL=http://keycloak:8080 >> .env
          echo AUTH_CLIENT_ID=webclient >> .env
          echo AUTH_CLIENT_SECRET=${{ secrets.AUTH_CLIENT_SECRET }} >> .env
          echo AUTH_REALM=development >> .env
          echo POSTGRES_HOST=db >> .env
          echo POSTGRES_PORT=5432 >> .env
          echo POSTGRES_DB=master >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo REDIS_HOST=redis >> .env
          echo REDIS_PORT=6379 >> .env
          echo KAFKA_HOST=kafka >> .env
          echo KAFKA_PORT=9092 >> .env
          cat .env

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker client image
        id: push-client
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./client
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker server image
        id: push-server
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}