name: Server linters

on: [pull_request, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.1"

      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2023.1.1"
