name: Tests

on: [pull_request, workflow_dispatch]
jobs:
  unit_tests:
    timeout-minutes: 3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.1"

      - name: Install server dependencies
        run: |
          cd server
          go mod download

      - name: Run Tests
        run: |
          cd server
          go test
